### ISSUE TITLE
Delay in Resolve loop

### ISSUE THREAD

**Issue by sizab** [phacility/libphutil#40]
I am using HTTPFuture to call two URLs on a RESTful API running one the same box.  I have error logged the start and end of the requests which sit behind the URLs so I know they have completed.  For some reason there is a 5 second delay between the calls completing and HTTPFuture knowing they have completed (between the URLs completing and $this->errorLogTiming("in loop"); in the example below) .  It only goes through the foreach loop twice - once for each call.  Any ideas on why this delay happens and how it can be removed?

Sample code ...

$futures = array();
$dynamoFuture = new \HTTPFuture($dynamoURL);
$futures[0] = $dynamoFuture;
		
$normalFuture = new \HTTPFuture($normalURL);
$futures[1] = $normalFuture;

$this->errorLogTiming("before loop");

foreach (Futures($futures) as $page => $future) {
	$this->errorLogTiming("in loop");
    	try {
		        $response_body = NULL;
		        list($response_body,$headers) = $future->resolvex();
		        $this->errorLogTiming("after resolve");
		    } catch (\Exception $e) {
		        continue;
		    }
		}
}

**Comment by chadlittle** [comment]
I believe this is outdated. If you still need assistance, please file your question at https://secure.phabricator.com/
